version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      xt9gaA0XUAt77B3Ix4kkV/mcObtHVWp1zoK1nE3DTdMSMsLORYqflIRdDBZIHOfJsq75Fm9YrhNxSoYZW0VqHdnzvbi4sXQzHCwMCmbi1IAZ+NjayworcIFHQzq7cFRCGqmIirXdv+5cjlHdeytw8U468PieVurWeD1ZGuqh4pjGxMNuvfOQlHp6gWR9Y1V1euHO1QIoGCCem4wDsjfrci/d3WijBHkHuAPfxc+rMkJZuWQOY2B3L2MB1pR9aDhDxmhV8rt2vNRqfd578v0ihEhQZmn4FS9C09AGcf+vz1Bed6D1dcyMNpd1cGXO1EE0qFO5Woqog2vZHBeZU5q6y2kYlCypke2oTp9e5T0phMYV62RMCj+fapWgHLb5nBgfj1vhyyt4wLhFfzSqYU04SVMUfHX0TadX4O79ikWUi7ZYqTkcVo601XBjOrnj/gIgjeV1hBhUOjwig07ESp+1OZTqynodpDguE3aYiXot2V4g8p97X0KaNly97gvaqmUU83241lgjUF8z3lDUBsfa/YjtESLyRbIXntFY5g59nqjQWFSnUjOxD0B9AuVl1Lea9kS9WmtIYOS2/ZfqJSNZXoJCkyXmfTIFyhumQ2H9ptQGVOluuw1ENb0do0dRawAKAanFz32R9qLv6orUJ1dBaFZzRlLWjVPdXIZlAveF0jM=
