version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      BWAGETzTbLkm0jAQ1z/CEEPkddou1MDpASa7/O6WspPxcjZn4gBPOylQpcQRhmXoOr5u+47BIbrn9dtanoWd/c2gyG6IQfGZWnI7KLypcwN9r3wNkHJLUWcFncXsCUTCJUtpniWA4Rd+Q0R/Brno6kE+rHl3AA0LVZkPzKimwGOSkMXum914KoND9PR1QwBS4dVFVhVH/3SvCeoujmKmeQbo+V2M2bB/HhSDjLKEyPupA+/6Q70z2u/eSVfIOBckAolgaNKsDRQSyirLg+A+Ck+8ka1fU+6waOrom9Aa+r/Y8raHM/v2st68eYRB3PKXQVATg0BoZmIcFCZgB1qKAhKr4+XuI2v6OK0IBfDx3iTWkkPXYLIvRVk3qsYHouRVtKMBr+lh2RTL2FN7D2SbXdqYn6iOO+srt6agvktK0Hmanw9D8YcL95srpsBQaDLv7iFSfl9hfm5Jb43cEZ+u8lcmo3e4mhbcRf0s5bAt+OReUNXTBPae+JyfEm/Btr5zmnHgTg3NqT9ctOi0UkzLAERNstjvba+6N9SEuGHgTuwF3DlO9If9xp7yDuXtmOhlyUy+TSe0hgEG2vFxppSVD0xHsAlmhpsDTB5El1Q4/lH5NRxUnlRTNGxTLYvW304fe6mQT+ds2uTG74YE8mz9G8WvBTZMd12gjs6Ig8Qocgg=
