#!/usr/bin/env node
'use strict'
// auto-generated by boundation, do not update manually
/** @type {typeof import("./compiled-types/bin.d.ts") } */
module.exports = require('editions').requirePackage(
	__dirname,
	require,
	'bin.js'
)
